2025-08-17 16:18:55 - INFO - Starting raw data extraction script
2025-08-17 16:18:55 - INFO - Snowflake connection config set
2025-08-17 16:18:55 - INFO - Snowflake Connector for Python Version: 3.17.1, Python Version: 3.13.7, Platform: Windows-11-10.0.26100-SP0
2025-08-17 16:18:55 - INFO - Connecting to GLOBAL Snowflake domain
2025-08-17 16:18:55 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x000002468D555A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /computeMetadata/v1/instance/service-accounts/default/email
2025-08-17 16:18:55 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x000002468D54E850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2025-08-17 16:18:55 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x000002468D54EC10>, 'Connection to 169.254.169.254 timed out. (connect timeout=0.2)')': /metadata/instance?api-version=2021-02-01
2025-08-17 16:18:55 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<snowflake.connector.vendored.urllib3.connection.HTTPConnection object at 0x000002468D50AFD0>, 'Connection to 169.254.169.254 timed out. (connect timeout=0.2)')': /metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com
2025-08-17 16:18:58 - INFO - Connected to Snowflake
2025-08-17 16:18:58 - INFO - Data read from Snowflake successfully
2025-08-17 16:18:58 - INFO - Data saved to partitioned folder: C:\Users\adity\Mtech\DMML\DMML_Assignment\customer_churn_pipeline\data\raw_ingested_data\2025-08-17\customer_churn_raw.csv
2025-08-17 16:18:58 - INFO - Read 1000 rows from Snowflake
2025-08-17 16:18:58 - INFO - Snowflake connection closed after successful data extraction
2025-08-17 16:18:58 - INFO - Script completed successfully
